server:
  port: 8080

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/andesfin}
    username: ${DB_USER:andesfin}
    password: ${DB_PASS:andesfin}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  #jackson:
    #serialization:
      #write-dates-as-timestamps: false
